# Google Cloud Platform Configuration

# Project Settings
project:
  project_id: "your-gcp-project-id"
  region: "us-central1"
  zone: "us-central1-a"

# Compute Instance Configuration
compute:
  instance_name: "claude-distillation-training"
  machine_type: "n1-standard-8"
  
  # GPU Configuration
  gpu:
    type: "nvidia-tesla-t4"
    count: 1
  
  # Instance Options
  preemptible: true
  boot_disk_size: "100GB"
  boot_disk_type: "pd-ssd"
  
  # Additional Disks
  data_disk:
    size: "500GB"
    type: "pd-ssd"
    mount_path: "/mnt/data"

# Container Configuration
container:
  image: "gcr.io/deeplearning-platform-release/pytorch-gpu.1-13"
  startup_script: |
    #!/bin/bash
    cd /home/jupyter
    git clone https://github.com/yeditepe/claude-to-codellama-distillation.git
    cd claude-to-codellama-distillation
    pip install -r requirements.txt
    export ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY}"

# Storage Configuration
storage:
  bucket_name: "claude-distillation-bucket"
  
  # Bucket structure
  paths:
    datasets: "gs://claude-distillation-bucket/datasets/"
    models: "gs://claude-distillation-bucket/models/"
    logs: "gs://claude-distillation-bucket/logs/"
    checkpoints: "gs://claude-distillation-bucket/checkpoints/"

# Networking
network:
  vpc_name: "default"
  subnet_name: "default"
  
  # Firewall
  firewall_rules:
    - name: "allow-jupyter"
      ports: ["8080", "8888"]
      source_ranges: ["0.0.0.0/0"]

# IAM and Security
iam:
  service_account: "claude-distillation@your-project.iam.gserviceaccount.com"
  scopes:
    - "https://www.googleapis.com/auth/cloud-platform"
    - "https://www.googleapis.com/auth/compute"
    - "https://www.googleapis.com/auth/devstorage.full_control"

# Monitoring and Logging
monitoring:
  enable_cloud_logging: true
  enable_cloud_monitoring: true
  
  # Custom metrics
  metrics:
    - name: "training_loss"
      type: "gauge"
    - name: "gpu_utilization"
      type: "gauge"
    - name: "memory_usage"
      type: "gauge"

# Cost Management
cost:
  budget_limit: 500  # USD
  alert_threshold: 0.8  # 80%
  
  # Automatic shutdown
  auto_shutdown:
    enabled: true
    idle_time: 3600  # 1 hour
    max_runtime: 43200  # 12 hours

# Environment Variables
environment:
  ANTHROPIC_API_KEY: "${ANTHROPIC_API_KEY}"
  WANDB_API_KEY: "${WANDB_API_KEY}"
  WANDB_PROJECT: "claude-to-codellama-distillation"
  
# Training Configuration
training:
  # Resource allocation
  cpu_count: 8
  memory_gb: 30
  gpu_memory_gb: 16
  
  # Training parameters
  batch_size: 4
  gradient_accumulation_steps: 4
  max_epochs: 3
  
  # Checkpointing
  checkpoint_frequency: 500  # steps
  save_frequency: 1000  # steps

# Deployment Options
deployment:
  # Development
  dev:
    machine_type: "n1-standard-4"
    gpu_type: "nvidia-tesla-t4"
    gpu_count: 1
    preemptible: true
    
  # Production
  prod:
    machine_type: "n1-standard-8"
    gpu_type: "nvidia-tesla-v100"
    gpu_count: 1
    preemptible: false
    
  # High-performance
  hpc:
    machine_type: "n1-standard-16"
    gpu_type: "nvidia-tesla-v100"
    gpu_count: 2
    preemptible: false