# Training Configuration for Knowledge Distillation

# Model Configuration
model:
  student_model: "codellama/CodeLlama-7b-hf"
  max_length: 2048
  cache_dir: "./cache/models"
  trust_remote_code: true

# LoRA Configuration
lora:
  r: 16
  alpha: 32
  dropout: 0.1
  target_modules:
    - "q_proj"
    - "k_proj" 
    - "v_proj"
    - "o_proj"
    - "gate_proj"
    - "up_proj"
    - "down_proj"
  bias: "none"
  task_type: "CAUSAL_LM"

# Quantization Configuration
quantization:
  load_in_4bit: true
  bnb_4bit_compute_dtype: "float16"
  bnb_4bit_quant_type: "nf4"
  bnb_4bit_use_double_quant: true

# Training Parameters
training:
  num_epochs: 3
  per_device_train_batch_size: 4
  per_device_eval_batch_size: 4
  gradient_accumulation_steps: 4
  learning_rate: 2e-4
  weight_decay: 0.01
  warmup_ratio: 0.1
  max_grad_norm: 1.0
  
  # Optimization
  optimizer: "adamw"
  lr_scheduler_type: "cosine"
  use_gradient_checkpointing: true
  fp16: true
  dataloader_pin_memory: false
  
  # Evaluation
  evaluation_strategy: "steps"
  eval_steps: 100
  save_strategy: "steps"
  save_steps: 500
  save_total_limit: 3
  load_best_model_at_end: true
  metric_for_best_model: "eval_loss"
  greater_is_better: false

# Knowledge Distillation
distillation:
  temperature: 4.0
  distillation_weight: 0.7
  task_weight: 0.3
  
  # Advanced techniques
  use_attention_transfer: true
  attention_weight: 0.1
  
  use_feature_matching: true
  feature_weight: 0.1
  
  use_progressive_distillation: true
  progressive_schedule: "linear"

# Data Configuration
data:
  dataset_path: "./data/generated"
  max_train_samples: null
  max_eval_samples: null
  preprocessing_num_workers: 4
  remove_unused_columns: false

# Logging and Monitoring
logging:
  output_dir: "./models/distilled_codellama"
  logging_dir: "./logs"
  logging_steps: 10
  report_to: "wandb"
  run_name: null
  
# Reproducibility
seed: 42
data_seed: 42